export const boardTypes = {
    //BOARD
    BUILD: 'BUILD',
    CLICKED: 'CLICKED',
    RIGHT_CLICKED: "RIGHT_CLICKED",
    REDUCE_MINE_LEFT: 'REDUCE_MINE_LEFT',
    INCREASE_MINE_LEFT: 'INCREASE_MINE_LEFT',
    CHECK_CELL: 'CHECK_CELL',
    RESET: 'RESET',
    EMPTY: 'EMPTY',

    //GAME
    TIME: 'TIME',
    CHANGE_LEVEL: 'CHANGE_LEVEL',
    CHANGE_SIZE: "CHANGE_SIZE",
    RESTART_GAME: "RESTART_GAME",
    PAUSE: 'PAUSE',
    FAILED: 'FAILED',
};

