export const boardTypes = {
    //BOARD
    BUILD: 'BUILD',
    CLICKED: 'CLICKED',
    RIGHT_CLICKED: "RIGHT_CLICKED",
    REDUCE_MINE_LEFT: 'REDUCE_MINE_LEFT',
    INCREASE_MINE_LEFT: 'INCREASE_MINE_LEFT',
    CHECK_CELL: 'CHECK_CELL',
    EMPTY: 'EMPTY',
    SAVE_CHANGE: 'SAVE_CHANGE',
    FLAG_TOGGLE: 'FLAG_TOGGLE',


    //GAME
    CHANGE_LEVEL: 'CHANGE_LEVEL',
    CHANGE_SIZE: "CHANGE_SIZE",
    RESTART_GAME: "RESTART_GAME",
    FAILED: 'FAILED',
    FINISH: 'FINISH',
    RESET: 'RESET'
};

